
#pragma once

#include <lib/libc/stdiox_legacy.h>

#include "./canvas/in/in.h"
#include "./canvas/out/out.h"

#define stdio_canvas_cell_compare stdio_legacy_cell_compare
#define stdio_canvas_cell_color_compare stdio_legacy_cell_color_compare
#define stdio_canvas_cell_foreground_color_compare stdio_legacy_cell__foreground_color_compare
#define stdio_canvas_cell_background_color_compare stdio_legacy_cell_background_color_compare

#define stdio_canvas_is_buffer_full stdio_legacy_canvas_is_buffer_full
#define stdio_canvas_screen_object_restore_defaults stdio_legacy_screen_object_restore_defaults
#define stdio_canvas_vga_position_get stdio_legacy_vga_position_get
#define stdio_canvas_move_to_y stdio_legacy_move_to_y
#define stdio_canvas_move_to_x stdio_legacy_move_to_x
#define stdio_canvas_get_last_valid_y stdio_legacy_get_last_valid_y
#define stdio_canvas_get_last_valid_x stdio_legacy_get_last_valid_x
