
#define ATA_IO_BASE 0x1F0

#define ATA_DATA_REGISTER 0x1F0

#define ATA_ERROR_REGISTER 0x1F1
#define ATA_FEATURES_REGISTERS 0x1F1

#define ATA_SECTOR_COUNT_REGISTER 0x1F2

#define ATA_SECTOR_NUMBER_LOW 0x1F3
#define ATA_SECTOR_NUMBER_MID 0x1F4
#define ATA_SECTOR_NUMBER_HIGH 0x1F5

#define ATA_HEAD_REGISTER 0x1F6

#define ATA_STATUS_REGISTER 0x1F7
#define ATA_COMMAND_REGISTER 0x1F7


void init_disk(void);
 
	
