
#pragma once

// XinFs
#define XANIN_FOPEN 10
#define XANIN_FREAD 11
#define XANIN_FWRITE 12
#define XANIN_FCLOSE 13

#define XANIN_OPEN 14
#define XANIN_READ 15
#define XANIN_WRITE 16
#define XANIN_CLOSE 17

// Memory Allocation

#define XANIN_ALLOCATE 100
#define XANIN_CALLOCATE 101
#define XANIN_REALLOCATE 102
#define XANIN_FREE 103

// Input

#define XANIN_INPUT_GET 200
#define XANIN_GETCHAR 201
#define XANIN_GETSCAN 202
#define XANIN_INPUTG 203
#define XANIN_KEYINFO_GET 204

// Disk
#define XANIN_DISK_READ 300
#define XANIN_DISK_WRITE 300