
;ORG!!!

;ATA REGISTERS
ATA_MASTER equ 0x1,
ATA_SLAVE equ 0x0,
ATA_FIRST_BUS equ 0x1F0,
ATA_SECONDARY_BUS equ 0x170,
ATA_DATA_REGISTER equ 0x0,
ATA_ERROR_REGISTER equ 0x1,
ATA_FEATURES_REGISTER equ 0x1,
ATA_SECTOR_COUNT_REGISTER equ 0x2,
ATA_SECTOR_NUMBER_LOW equ 0x3,
ATA_SECTOR_NUMBER_MID equ 0x4,
ATA_SECTOR_NUMBER_HIGH equ 0x5,
ATA_DRIVE_REGISTER equ 0x6,
ATA_STATUS_REGISTER equ 0x7,
ATA_COMMAND_REGISTER equ 0x7,
ATA_CONTROL_REGISTER equ 0x206


;ATA COMMANDS
ATA_IDENTIFY equ 0xEC,
ATA_READ equ 0x20,
ATA_WRITE equ 0x30,
ATA_FLUSH equ 0xE7

jmp init_disk


disk_status: db 0x0

init_disk:





