

#define PCI_ADDRESS_PORT 0xCF8
#define PCI_DATA_PORT 0xCFC

#define USB_CLASS_CONTROLLER_CODE 0x0C
#define USB_SUBCLASS_CONTROLLER_CODE 0x03

#define ENABLE_CONFIGURATION_SPACE_MAPPING 0x80000000


